/**/ddg_spice_github({
  "meta": {
    "Content-Type": "application/javascript; charset=utf-8",
    "X-RateLimit-Limit": "10",
    "X-RateLimit-Remaining": "9",
    "X-RateLimit-Reset": "1479982015",
    "Cache-Control": "no-cache",
    "X-GitHub-Media-Type": "github.v3",
    "status": 200
  },
  "data": {
    "total_count": 1,
    "incomplete_results": false,
    "items": [
      {
        "id": 326688,
        "name": "mustache.js",
        "full_name": "janl/mustache.js",
        "owner": {
          "login": "janl",
          "id": 11321,
          "avatar_url": "https://avatars.githubusercontent.com/u/11321?v=3",
          "gravatar_id": "",
          "url": "https://api.github.com/users/janl",
          "html_url": "https://github.com/janl",
          "followers_url": "https://api.github.com/users/janl/followers",
          "following_url": "https://api.github.com/users/janl/following{/other_user}",
          "gists_url": "https://api.github.com/users/janl/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/janl/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/janl/subscriptions",
          "organizations_url": "https://api.github.com/users/janl/orgs",
          "repos_url": "https://api.github.com/users/janl/repos",
          "events_url": "https://api.github.com/users/janl/events{/privacy}",
          "received_events_url": "https://api.github.com/users/janl/received_events",
          "type": "User",
          "site_admin": false
        },
        "private": false,
        "html_url": "https://github.com/janl/mustache.js",
        "description": "Minimal templating with {{mustaches}} in JavaScript",
        "fork": false,
        "url": "https://api.github.com/repos/janl/mustache.js",
        "forks_url": "https://api.github.com/repos/janl/mustache.js/forks",
        "keys_url": "https://api.github.com/repos/janl/mustache.js/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/janl/mustache.js/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/janl/mustache.js/teams",
        "hooks_url": "https://api.github.com/repos/janl/mustache.js/hooks",
        "issue_events_url": "https://api.github.com/repos/janl/mustache.js/issues/events{/number}",
        "events_url": "https://api.github.com/repos/janl/mustache.js/events",
        "assignees_url": "https://api.github.com/repos/janl/mustache.js/assignees{/user}",
        "branches_url": "https://api.github.com/repos/janl/mustache.js/branches{/branch}",
        "tags_url": "https://api.github.com/repos/janl/mustache.js/tags",
        "blobs_url": "https://api.github.com/repos/janl/mustache.js/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/janl/mustache.js/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/janl/mustache.js/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/janl/mustache.js/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/janl/mustache.js/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/janl/mustache.js/languages",
        "stargazers_url": "https://api.github.com/repos/janl/mustache.js/stargazers",
        "contributors_url": "https://api.github.com/repos/janl/mustache.js/contributors",
        "subscribers_url": "https://api.github.com/repos/janl/mustache.js/subscribers",
        "subscription_url": "https://api.github.com/repos/janl/mustache.js/subscription",
        "commits_url": "https://api.github.com/repos/janl/mustache.js/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/janl/mustache.js/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/janl/mustache.js/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/janl/mustache.js/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/janl/mustache.js/contents/{+path}",
        "compare_url": "https://api.github.com/repos/janl/mustache.js/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/janl/mustache.js/merges",
        "archive_url": "https://api.github.com/repos/janl/mustache.js/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/janl/mustache.js/downloads",
        "issues_url": "https://api.github.com/repos/janl/mustache.js/issues{/number}",
        "pulls_url": "https://api.github.com/repos/janl/mustache.js/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/janl/mustache.js/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/janl/mustache.js/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/janl/mustache.js/labels{/name}",
        "releases_url": "https://api.github.com/repos/janl/mustache.js/releases{/id}",
        "deployments_url": "https://api.github.com/repos/janl/mustache.js/deployments",
        "created_at": "2009-10-04T23:41:19Z",
        "updated_at": "2016-11-24T04:20:57Z",
        "pushed_at": "2016-11-14T17:51:38Z",
        "git_url": "git://github.com/janl/mustache.js.git",
        "ssh_url": "git@github.com:janl/mustache.js.git",
        "clone_url": "https://github.com/janl/mustache.js.git",
        "svn_url": "https://github.com/janl/mustache.js",
        "homepage": "http://mustache.github.com/",
        "size": 2111,
        "stargazers_count": 10078,
        "watchers_count": 10078,
        "language": "JavaScript",
        "has_issues": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": true,
        "forks_count": 1956,
        "mirror_url": null,
        "open_issues_count": 55,
        "forks": 1956,
        "open_issues": 55,
        "watchers": 10078,
        "default_branch": "master",
        "score": 113.167534
      }
    ]
  }
})
